version: "3.8"
services:
  frontend:
    build: ./client
    volumes:
      - ./client:/usr/home/news-app-frontend
    image: rahulargusoft/news-app-frontend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      backend:
        condition: service_started
  backend:
    build: ./server
    image: rahulargusoft/news-app-backend
    ports:
      - 3000:3000
    env_file:
      - ./server/.env
    restart: always
    volumes:
      - ./server:/usr/home/news-app-backend
